#!/usr/bin/env xemacs-script
;;; config.values.el --- create config.values.in from ../configure.ac

;; Copyright (C) 1997, 1999 Martin Buchholz
;; Copyright (C) 2026 Free Software Foundation

;; Author:	Martin Buchholz, Aidan Kehoe
;; Maintainer:	Aidan Kehoe
;; Keywords:	configure elisp report-xemacs-bugs

;; This file is part of XEmacs.
;; 
;; XEmacs is free software: you can redistribute it and/or modify it
;; under the terms of the GNU General Public License as published by the
;; Free Software Foundation, either version 3 of the License, or (at your
;; option) any later version.
;; 
;; XEmacs is distributed in the hope that it will be useful, but WITHOUT
;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;; for more details.
;; 
;; You should have received a copy of the GNU General Public License
;; along with XEmacs.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; Extract all the @foo@ configuration symbols from ../configure to make them
;; available to elisp later (see config.el).
;; Primarily useful for creating ridiculously verbose bug reports, but also
;; helpful in moving C utility programs to Lisp.
;;
;; See lisp/config.el, ../configure.ac for more details.
;;
;; This script needs only to be run occasionally (before a Net release) by an
;; XEmacs Maintainer (consider yourself so blessed, if you are actually
;; reading this commentary).

(let ((configure (expand-file-name "configure" source-directory))
      subst)
  (unless (file-readable-p configure)
    (error 'file-error "Cannot read file" configure))
  (with-temp-buffer
    (insert-file-contents configure)
    (goto-char (point-min))
    (if (not (search-forward "\nac_subst_vars='" nil t))
	(error 'syntax-error "Cannot find ac_subst_vars in file"
	       configure)
      (setq subst (split-string-by-char
		   (buffer-substring
		    (point)
		    (progn (skip-chars-forward "^'")
			   (point)))
		   ?\n)))
    (goto-char (point-min))
    (setq subst
          (delete-duplicates (sort subst #'string-lessp) :test #'equal))
    (erase-buffer)
    (kill-all-local-variables)
    (insert "\
;;; Do not edit this file!
;;; This file was automatically generated, by config.values.elc, from
;;; configure, which was itself automatically generated from configure.ac.
;;;
;;; See lisp/config.el for details on how this file is used.
;;;
;;; You are trapped in a twisty maze of strange-looking files, all autogenerated...

;;; configure        is created, from configure.ac,     by autoconf
;;; config.values.in is created, from configure,        by config.values.el
;;; config.values    is created, from config.values.in, by configure
;;; config.values    is read by lisp/config.el,
;;;                  to create the (Lisp object) config-value-hash-table

;;; Variables defined in configure by AC_SUBST follow:
;;; (These are used in Makefiles)

")
    (mapc #'(lambda (string)
	      (format-into (current-buffer) "%s \"@%s@\"\n"
			   string string))
	  subst)
    (insert "
;;; Variables defined in configure by AC_DEFINE and AC_DEFINE_UNQUOTED follow:
;;; (These are used in C code)
")
    (write-file (expand-file-name "config.values.in" doc-directory))
    (kill-buffer (current-buffer))))

;;; config.values.el ends here
