;;; regexp-opt.el --- generate efficient regexps to match strings

;; Copyright (C) 1994-2026 Free Software Foundation, Inc.

;; Author: Simon Marshall <simon@gnu.org>
;; Maintainer: FSF
;; Keywords: strings, regexps, extensions

;; This file is part of XEmacs.

;; XEmacs is free software: you can redistribute it and/or modify it
;; under the terms of the GNU General Public License as published by the
;; Free Software Foundation, either version 3 of the License, or (at your
;; option) any later version.

;; XEmacs is distributed in the hope that it will be useful, but WITHOUT
;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;; for more details.

;; You should have received a copy of the GNU General Public License
;; along with XEmacs.  If not, see <http://www.gnu.org/licenses/>.

;;; Synched up with: GNU Emacs 31.0.5. regexp-opt-charset is very different 
;;;                  in its implementation but the rest of the code is
;;;                  essentially identical.  The APIs are compatible and
;;;                  return compatible (if not exactly the same) regexps.

;;; Commentary:

;; The "opt" in "regexp-opt" stands for "optim\\(?:al\\|i\\(?:se\\|ze\\)\\)".
;;
;; This package generates a regexp from a given list of strings (which matches
;; one of those strings) so that the regexp generated by:
;;
;; (regexp-opt strings)
;;
;; is equivalent to, but more efficient than, the regexp generated by:
;;
;; (mapconcat 'regexp-quote strings "\\|")
;;
;; For example:
;;
;; (let ((strings '("cond" "if" "when" "unless" "while"
;; 		    "let" "let*" "progn" "prog1" "prog2"
;; 		    "save-restriction" "save-excursion" "save-window-excursion"
;; 		    "save-current-buffer" "save-match-data"
;; 		    "catch" "throw" "unwind-protect" "condition-case")))
;;   (concat "(" (regexp-opt strings t) "\\>"))
;;  => "(\\(c\\(?:atch\\|ond\\(?:ition-case\\)?\\)\\|if\\|let\\*?\\|prog[12n]\\|save-\\(?:current-buffer\\|excursion\\|match-data\\|restriction\\|window-excursion\\)\\|throw\\|un\\(?:less\\|wind-protect\\)\\|wh\\(?:en\\|ile\\)\\)\\>"
;;
;; Searching using the above example `regexp-opt' regexp takes approximately
;; two-thirds of the time taken using the equivalent `mapconcat' regexp.

;; Since this package was written to produce efficient regexps, not regexps
;; efficiently, it is probably not a good idea to in-line too many calls in
;; your code, unless you use the following trick with `eval-when-compile':
;;
;; (defvar definition-regexp
;;   (eval-when-compile
;;     (concat "^("
;;             (regexp-opt '("defun" "defsubst" "defmacro" "defalias"
;;                           "defvar" "defconst") t)
;;             "\\>")))
;;
;; The `byte-compile' code will be as if you had defined the variable thus:
;;
;; (defvar definition-regexp
;;   "^(\\(def\\(alias\\|const\\|macro\\|subst\\|un\\|var\\)\\)\\>")
;;
;; Note that if you use this trick for all instances of `regexp-opt' and
;; `regexp-opt-depth' in your code, regexp-opt.el would only have to be loaded
;; at compile time.  But note also that using this trick means that should
;; regexp-opt.el be changed, perhaps to fix a bug or to add a feature to
;; improve the efficiency of `regexp-opt' regexps, you would have to recompile
;; your code for such changes to have effect in your code.

;; Originally written for font-lock.el, from an idea from Stig's hl319.el, with
;; thanks for ideas also to Michael Ernst, Bob Glickstein, Dan Nicolaescu and
;; Stefan Monnier.
;; No doubt `regexp-opt' doesn't always produce optimal regexps, so code, ideas
;; or any other information to improve things are welcome.
;;
;; One possible improvement would be to compile '("aa" "ab" "ba" "bb")
;; into "[ab][ab]" rather than "a[ab]\\|b[ab]".  I'm not sure it's worth
;; it but if someone knows how to do it without going through too many
;; contortions, I'm all ears.

;;; Code:

;;;###autoload
(defun regexp-opt (strings &optional paren)
  "Return a regexp which matches exactly those strings in STRINGS.

Regexp special characters in the elements of STRINGS will not be treated
specially in matching; they will be escaped as necessary in constructing the
regexp.

The optional argument PAREN can be any of the following:

a string
    the resulting regexp is preceded by PAREN and followed by
    \\), e.g.  use \"\\\\(?1:\" to produce an explicitly numbered
    group.

`words' (the symbol, which you likely need to quote)
    the resulting regexp is surrounded by \\=\\<\\( and \\)\\>.

`symbols' (a symbol)
    the resulting regexp is surrounded by \\_<\\( and \\)\\_>.

another non-nil value
    the resulting regexp is surrounded by \\( and \\).

nil
    the resulting regexp is surrounded by \\(?: and \\), if it is
    necessary to ensure that a postfix operator appended to it will
    apply to the whole expression.

The returned regexp is ordered in such a way that it will always
match the longest string possible.

Up to reordering, the resulting regexp is equivalent to but
usually more efficient than that of a simplified version:

 (defun simplified-regexp-opt (strings &optional paren)
   (let ((parens
          (cond ((stringp paren)     (cons paren \"\\\\)\"))
                ((eq paren \\='words)   \\='(\"\\\\\\=<\\\\(\" . \"\\\\)\\\\>\"))
                ((eq paren \\='symbols) \\='(\"\\\\_<\\\\(\" . \"\\\\)\\\\_>\"))
                ((null paren)        \\='(\"\\\\(?:\" . \"\\\\)\"))
                (t                   \\='(\"\\\\(\" . \"\\\\)\")))))
     (concat (car parens)
             (mapconcat \\='regexp-quote strings \"\\\\|\")
             (cdr parens))))"
  (save-match-data
    ;; Recurse on the sorted list.
    (let* ((max-lisp-eval-depth (* 1024 1024))
	   (max-specpdl-size (* 1024 1024))
	   (completion-ignore-case nil)
	   (completion-regexp-list nil)
	   (open (cond ((stringp paren) paren) (paren "\\(")))
	   (re (if strings
		   (regexp-opt-group
                    (delete-dups (sort (copy-sequence strings) 'string-lessp))
                    (or open t) (not open))
		 (concat (or open "\\(?:") "\\`a\\`\\)"))))
      (cond ((eq paren 'words) (concat "\\<" re "\\>"))
	    ((eq paren 'symbols) (concat "\\_<" re "\\_>"))
	    (t re)))))

;; XEmacs change; this functionality is in bytecomp.el in GNU Emacs.
;;;###autoload
(define-compiler-macro regexp-opt (&whole form &rest arguments)
  (if (and (cl-const-exprs-p (cdr form))
           (function-allows-args #'regexp-opt (length (cdr form))))
      (condition-case nil (eval form) (error form))
    form))

;; XEmacs; added here. This is in subr.el in GNU; reflects tip as of
;; 2026-04-06.
;;;###autoload
(defun subregexp-context-p (regexp pos &optional start)
  "Return non-nil if POS is in a normal subregexp context in REGEXP.
A subregexp context is one where a sub-regexp can appear.
A non-subregexp context is for example within brackets, or within a
repetition bounds operator `\\=\\{...\\}', or right after a `\\'.
If START is non-nil, it should be a position in REGEXP, smaller
than POS, and known to be in a subregexp context."
  ;; Here's one possible implementation, with the great benefit that it
  ;; reuses the regexp-matcher's own parser, so it understands all the
  ;; details of the syntax.  A disadvantage is that it needs to match the
  ;; error string
  (condition-case error
      (progn
        (string-match-p (substring regexp (or start 0) pos) "")
        t)
    (invalid-regexp
     (not (member (cadr error) '("Unmatched [ or [^"
                                 "Unmatched \\{"
                                 "Trailing backslash"))))))

;;;###autoload
(defun regexp-opt-depth (regexp)
  "Return the depth of REGEXP.
This means the number of non-shy regexp grouping constructs
\(parenthesized subexpressions) in REGEXP."
  ;; Hack to signal an error if REGEXP does not have balanced parentheses.
  (string-match-p regexp "")
  (save-match-data
    ;; Count the number of open parentheses in REGEXP.
    (let ((count 0) start last)
      (while (string-match "\\\\(\\(\\?:\\)?" regexp start)
	(setq start (match-end 0))	      ; Start of next search.
	(when (and (not (match-beginning 1))
		   (subregexp-context-p regexp (match-beginning 0) last))
	  ;; It's not a shy group and it's not inside brackets or after
	  ;; a backslash: it's really a group-open marker.
	  (setq last start	    ; Speed up next #'subregexp-context-p
                count (1+ count))))
      count)))

;;; Workhorse functions.

(defun regexp-opt-group (strings &optional paren lax)
  "Return a regexp to match a string in STRINGS.
If PAREN non-nil, output regexp parentheses around returned regexp.
If LAX non-nil, don't output parentheses if it doesn't require them.
Merges keywords to avoid backtracking in Emacs' regexp matcher.

The basic idea is to find the shortest common prefix or suffix, remove it
and recurse.  If there is no prefix, we divide the list into two so that
\(at least) one half will have at least a one-character common prefix.

Also we delay the addition of grouping parenthesis as long as possible
until we're sure we need them, and try to remove one-character sequences
so we can use character sets rather than grouping parenthesis."
  (let* ((open-group (cond ((stringp paren) paren) (paren "\\(?:") (t "")))
	 (close-group (if paren "\\)" ""))
	 (open-charset (if lax "" open-group))
	 (close-charset (if lax "" close-group)))
    (cond
     ;;
     ;; If there are no strings, just return the empty string.
     ((eql (length strings) 0)
      "")
     ;;
     ;; If there is only one string, just return it.
     ((eql (length strings) 1)
      (if (eql (length (car strings)) 1)
	  (concat open-charset (regexp-quote (car strings)) close-charset)
	(concat open-group (regexp-quote (car strings)) close-group)))
     ;;
     ;; If there is an empty string, remove it and recurse on the rest.
     ((eql (length (car strings)) 0)
      (concat open-charset
	      (regexp-opt-group (cdr strings) t t) "?"
	      close-charset))
     ;;
     ;; If there are several one-char strings, use charsets.
     ((and (eql (length (car strings)) 1)
           (member* 1 (cdr strings) :key #'length))
      (let (letters rest)
	;; Collect one-char strings
	(dolist (s strings)
	  (if (eql (length s) 1) (push (aref s 0) letters) (push s rest)))
	(if rest
	    ;; Several one-char strings: take them and recurse
	    ;; on the rest (first so as to match the longest).
	    (concat open-group
		    (regexp-opt-group (nreverse rest))
		    "\\|" (regexp-opt-charset letters)
		    close-group)
	  ;; All are one-char strings: just return a character set.
	  (concat open-charset
		  (regexp-opt-charset letters)
		  close-charset))))
     ;;
     ;; We have a list of different length strings.
     (t
      (let ((prefix (try-completion "" strings)))
	(if (> (length prefix) 0)
	    ;; Common prefix: take it and recurse on the suffixes.
	    (let* ((n (length prefix))
		   (suffixes (mapcar (lambda (s) (substring s n)) strings)))
	      (concat open-group
		      (regexp-quote prefix)
		      (regexp-opt-group suffixes t t)
		      close-group))
	  (let ((xiffus (try-completion "" (mapcar #'reverse strings))))
	    (if (> (length xiffus) 0)
		;; Common suffix: take it and recurse on the prefixes.
		(let* ((n (- (length xiffus)))
		       (prefixes
			;; Sorting is necessary in cases such as ("ad" "d").
			(sort (mapcar (lambda (s) (substring s 0 n)) strings)
			      'string-lessp)))
		  (concat open-group
			  (regexp-opt-group prefixes t t)
			  (regexp-quote (nreverse xiffus))
			  close-group))

	      ;; Otherwise, divide the list into those that start with a
	      ;; particular letter and those that do not, and recurse on them.
	      (let* ((half1 (all-completions (substring (car strings) 0 1)
                                             strings))
		     (half2 (nthcdr (length half1) strings)))
		(concat open-group
			(regexp-opt-group half1)
			"\\|" (regexp-opt-group half2)
			close-group))))))))))

(defun regexp-opt-charset (chars)
  "Return a regexp character set to match CHARS, a list of characters.

If CHARS is the empty list, return a regexp that never matches anything.  If
CHARS is one in length, the result may be a (possibly-quoted) character rather
than a character set."
  (let* ((char-table (make-char-table 'generic)) (count 0)
         charset bracket dash caret)
    ;; The basic idea is to find character ranges, something the char table
    ;; implementation does for us for free, thank you Ben Wing.
    ;;
    ;; Also we take care in the position of character set meta characters in
    ;; the character set regexp.
    (dolist (character chars)
      (check-type character character)
      (incf count)
      (case character
	(?\]
	 (setq bracket (list character)))
	(?^
	 (setq caret (list character)))
	(?-
	 (setq dash (list character)))
	(otherwise
         (put-char-table character t char-table))))

    ;; Make a character set from the map using ranges where applicable.
    (map-char-table
     (lambda (c v)
       (setq charset (if (consp c)
                         (list* (car c) ?- (cdr c) charset)
                       (cons c charset)))
       nil)
     char-table)

    (case count
      (0 "\\`a\\`")
      (1 (regexp-quote (concat (or charset bracket caret dash))))
      (otherwise
       ;; Make sure a caret is not first and a dash is first or last.
       (if (or charset bracket)
           (concat "[" bracket charset caret dash "]")
         (concat "[" dash caret "]"))))))

(provide 'regexp-opt)

;;; regexp-opt.el ends here
