/* This file was automatically generated by ../lisp/gtk-marshal.el */
/* DO NOT EDIT BY HAND!!! */
#define GTK_VALUE_ARRAY(x) GTK_VALUE_POINTER(x)

#define GTK_VALUE_LIST(x) GTK_VALUE_POINTER(x)


static void
emacs_gtk_marshal_BOOL__OBJECT_INT (ffi_actual_function func,
                                    GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT_OBJECT_OBJECT (ffi_actual_function func,
                                              GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[3], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT_OBJECT (ffi_actual_function func,
                                       GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT_POINTER (ffi_actual_function func,
                                        GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT_STRING (ffi_actual_function func,
                                       GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__OBJECT (ffi_actual_function func,
                                GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[1], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_BOOL__POINTER_BOOL (ffi_actual_function func,
                                      GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[2], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_boolean (&args[1])));
}

static void
emacs_gtk_marshal_BOOL__POINTER (ffi_actual_function func,
                                 GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[1], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_BOOL__NONE (ffi_actual_function func,
                              GValue *args)
{
  __BOOL_fn rfunc = (__BOOL_fn) func;

  g_value_init (&args[0], G_TYPE_BOOLEAN);
  g_value_set_boolean (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_FLOAT__OBJECT_FLOAT (ffi_actual_function func,
                                       GValue *args)
{
  __FLOAT_fn rfunc = (__FLOAT_fn) func;

  g_value_init (&args[2], G_TYPE_FLOAT);
  g_value_set_float (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1])));
}

static void
emacs_gtk_marshal_FLOAT__OBJECT (ffi_actual_function func,
                                 GValue *args)
{
  __FLOAT_fn rfunc = (__FLOAT_fn) func;

  g_value_init (&args[1], G_TYPE_FLOAT);
  g_value_set_float (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_INT__BOOL (ffi_actual_function func,
                             GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_boolean (&args[0])));
}

static void
emacs_gtk_marshal_INT__INT (ffi_actual_function func,
                            GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_int (&args[0])));
}

static void
emacs_gtk_marshal_INT__INT_INT (ffi_actual_function func,
                                GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_ARRAY (ffi_actual_function func,
                                     GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_INT_ARRAY (ffi_actual_function func,
                                         GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_pointer (&args[2])));
}

static void
emacs_gtk_marshal_INT__OBJECT_INT_INT (ffi_actual_function func,
                                       GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_INT__OBJECT_INT_STRING (ffi_actual_function func,
                                          GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_string (&args[2])));
}

static void
emacs_gtk_marshal_INT__OBJECT_INT (ffi_actual_function func,
                                   GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_OBJECT (ffi_actual_function func,
                                      GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_POINTER_INT_INT (ffi_actual_function func,
                                               GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[4], G_TYPE_INT);
  g_value_set_int (&args[4],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3])));
}

static void
emacs_gtk_marshal_INT__OBJECT_POINTER_INT (ffi_actual_function func,
                                           GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_INT__OBJECT_POINTER (ffi_actual_function func,
                                       GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT_STRING (ffi_actual_function func,
                                      GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_INT__OBJECT (ffi_actual_function func,
                               GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_INT__POINTER_INT (ffi_actual_function func,
                                    GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_INT__POINTER_STRING_INT (ffi_actual_function func,
                                           GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_INT__POINTER_STRING_STRING (ffi_actual_function func,
                                              GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[3], G_TYPE_INT);
  g_value_set_int (&args[3],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_string (&args[2])));
}

static void
emacs_gtk_marshal_INT__POINTER_STRING (ffi_actual_function func,
                                       GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[2], G_TYPE_INT);
  g_value_set_int (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_INT__POINTER (ffi_actual_function func,
                                GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_INT__STRING_STRING_INT_ARRAY (ffi_actual_function func,
                                                GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[4], G_TYPE_INT);
  g_value_set_int (&args[4],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3])));
}

static void
emacs_gtk_marshal_INT__STRING (ffi_actual_function func,
                               GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[1], G_TYPE_INT);
  g_value_set_int (&args[1],
    (*rfunc) (g_value_get_string (&args[0])));
}

static void
emacs_gtk_marshal_INT__NONE (ffi_actual_function func,
                             GValue *args)
{
  __INT_fn rfunc = (__INT_fn) func;

  g_value_init (&args[0], G_TYPE_INT);
  g_value_set_int (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_LIST__OBJECT (ffi_actual_function func,
                                GValue *args)
{
  __LIST_fn rfunc = (__LIST_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_LIST__NONE (ffi_actual_function func,
                              GValue *args)
{
  __LIST_fn rfunc = (__LIST_fn) func;

  g_value_init (&args[0], G_TYPE_POINTER);
  g_value_set_pointer (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_NONE__BOOL (ffi_actual_function func,
                              GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_boolean (&args[0]));
}

static void
emacs_gtk_marshal_NONE__INT_INT_INT_INT (ffi_actual_function func,
                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__INT_INT (ffi_actual_function func,
                                 GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]));
}

static void
emacs_gtk_marshal_NONE__INT (ffi_actual_function func,
                             GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_int (&args[0]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_BOOL_INT (ffi_actual_function func,
                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_boolean (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_BOOL (ffi_actual_function func,
                                     GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_boolean (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_BOOL (ffi_actual_function func,
                                                       GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_boolean (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func,
                                                        GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT (ffi_actual_function func,
                                                  GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT (ffi_actual_function func,
                                            GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_FLOAT (ffi_actual_function func,
                                      GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_BOOL (ffi_actual_function func,
                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_boolean (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT_BOOL (ffi_actual_function func,
                                               GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_boolean (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT (ffi_actual_function func,
                                          GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_float (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY (ffi_actual_function func,
                                                                            GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_pointer (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]),
      g_value_get_pointer (&args[7]),
      g_value_get_pointer (&args[8]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY (ffi_actual_function func,
                                              GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_FLOAT_FLOAT (ffi_actual_function func,
                                                    GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT_INT (ffi_actual_function func,
                                                GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT (ffi_actual_function func,
                                            GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER_POINTER (ffi_actual_function func,
                                                        GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_pointer (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER (ffi_actual_function func,
                                                GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING_INT_POINTER_POINTER (ffi_actual_function func,
                                                                   GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_string (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING (ffi_actual_function func,
                                               GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_string (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_INT (ffi_actual_function func,
                                        GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_OBJECT (ffi_actual_function func,
                                           GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_object (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_POINTER (ffi_actual_function func,
                                            GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_pointer (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT_STRING (ffi_actual_function func,
                                           GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_string (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_INT (ffi_actual_function func,
                                    GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_LIST_INT (ffi_actual_function func,
                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_LIST (ffi_actual_function func,
                                     GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT_INT (ffi_actual_function func,
                                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_boolean (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT (ffi_actual_function func,
                                                     GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_boolean (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL (ffi_actual_function func,
                                                 GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_boolean (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_FLOAT_INT (ffi_actual_function func,
                                                 GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT_INT_INT_INT_INT (ffi_actual_function func,
                                                                       GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]),
      g_value_get_int (&args[7]),
      g_value_get_int (&args[8]),
      g_value_get_int (&args[9]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT (ffi_actual_function func,
                                                       GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT (ffi_actual_function func,
                                                   GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT (ffi_actual_function func,
                                               GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT (ffi_actual_function func,
                                           GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_INT (ffi_actual_function func,
                                                  GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT_INT (ffi_actual_function func,
                                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]),
      g_value_get_object (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT (ffi_actual_function func,
                                                     GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]),
      g_value_get_object (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_POINTER_POINTER_INT_INT (ffi_actual_function func,
                                                                      GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_pointer (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT (ffi_actual_function func,
                                              GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_object (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_POINTER (ffi_actual_function func,
                                               GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_pointer (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_INT_INT_INT_INT_INT (ffi_actual_function func,
                                                                  GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]),
      g_value_get_int (&args[7]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING_INT (ffi_actual_function func,
                                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_string (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING (ffi_actual_function func,
                                                     GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_string (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING (ffi_actual_function func,
                                              GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]),
      g_value_get_string (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_OBJECT (ffi_actual_function func,
                                       GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_BOOL (ffi_actual_function func,
                                             GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_boolean (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_FLOAT_FLOAT (ffi_actual_function func,
                                                        GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT_INT (ffi_actual_function func,
                                                    GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT (ffi_actual_function func,
                                                GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER_POINTER (ffi_actual_function func,
                                                            GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_pointer (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER (ffi_actual_function func,
                                                    GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING_INT_POINTER_POINTER (ffi_actual_function func,
                                                                       GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_string (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING (ffi_actual_function func,
                                                   GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_string (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_INT (ffi_actual_function func,
                                            GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_INT_INT_INT_INT_INT_INT (ffi_actual_function func,
                                                                        GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]),
      g_value_get_int (&args[7]),
      g_value_get_int (&args[8]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER_STRING_INT (ffi_actual_function func,
                                                                   GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_string (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER (ffi_actual_function func,
                                                        GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER (ffi_actual_function func,
                                                GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER_STRING_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL (ffi_actual_function func,
                                                                                             GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_pointer (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]),
      g_value_get_pointer (&args[7]),
      g_value_get_boolean (&args[8]),
      g_value_get_boolean (&args[9]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_POINTER (ffi_actual_function func,
                                        GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_BOOL (ffi_actual_function func,
                                            GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_boolean (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_INT_INT_INT (ffi_actual_function func,
                                                   GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT_INT (ffi_actual_function func,
                                                           GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT (ffi_actual_function func,
                                                       GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING_STRING (ffi_actual_function func,
                                              GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_string (&args[2]));
}

static void
emacs_gtk_marshal_NONE__OBJECT_STRING (ffi_actual_function func,
                                       GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]));
}

static void
emacs_gtk_marshal_NONE__OBJECT (ffi_actual_function func,
                                GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_object (&args[0]));
}

static void
emacs_gtk_marshal_NONE__POINTER_BOOL (ffi_actual_function func,
                                      GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_boolean (&args[1]));
}

static void
emacs_gtk_marshal_NONE__POINTER_INT_INT (ffi_actual_function func,
                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2]));
}

static void
emacs_gtk_marshal_NONE__POINTER_INT (ffi_actual_function func,
                                     GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_int (&args[1]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT_INT_INT (ffi_actual_function func,
                                                                      GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]),
      g_value_get_int (&args[7]),
      g_value_get_int (&args[8]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT (ffi_actual_function func,
                                                              GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_boolean (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT_INT_INT (ffi_actual_function func,
                                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT (ffi_actual_function func,
                                                 GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING_INT (ffi_actual_function func,
                                                                    GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_string (&args[5]),
      g_value_get_int (&args[6]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING (ffi_actual_function func,
                                                                GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_string (&args[5]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_POINTER (ffi_actual_function func,
                                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_pointer (&args[3]));
}

static void
emacs_gtk_marshal_NONE__POINTER_POINTER (ffi_actual_function func,
                                         GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1]));
}

static void
emacs_gtk_marshal_NONE__POINTER_STRING_STRING (ffi_actual_function func,
                                               GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_string (&args[2]));
}

static void
emacs_gtk_marshal_NONE__POINTER_STRING (ffi_actual_function func,
                                        GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1]));
}

static void
emacs_gtk_marshal_NONE__POINTER (ffi_actual_function func,
                                 GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) (g_value_get_pointer (&args[0]));
}

static void
emacs_gtk_marshal_NONE__NONE (ffi_actual_function func,
                              GValue *args)
{
  __NONE_fn rfunc = (__NONE_fn) func;
   (*rfunc) ();
}

static void
emacs_gtk_marshal_OBJECT__BOOL_BOOL_INT (ffi_actual_function func,
                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_boolean (&args[0]),
      g_value_get_boolean (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__BOOL_INT (ffi_actual_function func,
                                    GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_boolean (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func,
                                                               GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[6], G_TYPE_OBJECT);
  g_value_set_object (&args[6],
    (*rfunc) (g_value_get_float (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]),
      g_value_get_float (&args[5])));
}

static void
emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func,
                                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[5], G_TYPE_OBJECT);
  g_value_set_object (&args[5],
    (*rfunc) (g_value_get_float (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4])));
}

static void
emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func,
                                                   GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[4], G_TYPE_OBJECT);
  g_value_set_object (&args[4],
    (*rfunc) (g_value_get_float (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3])));
}

static void
emacs_gtk_marshal_OBJECT__INT_ARRAY (ffi_actual_function func,
                                     GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__INT_BOOL_BOOL (ffi_actual_function func,
                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_boolean (&args[1]),
      g_value_get_boolean (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__INT_INT_ARRAY (ffi_actual_function func,
                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_pointer (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__INT_INT_BOOL (ffi_actual_function func,
                                        GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_boolean (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__INT_INT_STRING (ffi_actual_function func,
                                          GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_string (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__INT_INT (ffi_actual_function func,
                                   GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__INT (ffi_actual_function func,
                               GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[1], G_TYPE_OBJECT);
  g_value_set_object (&args[1],
    (*rfunc) (g_value_get_int (&args[0])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_FLOAT_INT (ffi_actual_function func,
                                            GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[3], G_TYPE_OBJECT);
  g_value_set_object (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_INT (ffi_actual_function func,
                                      GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_OBJECT (ffi_actual_function func,
                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_object (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT_INT (ffi_actual_function func,
                                                             GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[7], G_TYPE_OBJECT);
  g_value_set_object (&args[7],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5]),
      g_value_get_int (&args[6])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT (ffi_actual_function func,
                                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[6], G_TYPE_OBJECT);
  g_value_set_object (&args[6],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_int (&args[5])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT (ffi_actual_function func,
                                                 GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[4], G_TYPE_OBJECT);
  g_value_set_object (&args[4],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_int (&args[2]),
      g_value_get_int (&args[3])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT_STRING (ffi_actual_function func,
                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__OBJECT (ffi_actual_function func,
                                  GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[1], G_TYPE_OBJECT);
  g_value_set_object (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_OBJECT__POINTER_POINTER (ffi_actual_function func,
                                           GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__POINTER_STRING (ffi_actual_function func,
                                          GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__POINTER (ffi_actual_function func,
                                   GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[1], G_TYPE_OBJECT);
  g_value_set_object (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_FLOAT_FLOAT_FLOAT_BOOL (ffi_actual_function func,
                                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[5], G_TYPE_OBJECT);
  g_value_set_object (&args[5],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_boolean (&args[4])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_INT_STRING_STRING (ffi_actual_function func,
                                                    GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[4], G_TYPE_OBJECT);
  g_value_set_object (&args[4],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_string (&args[3])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_OBJECT (ffi_actual_function func,
                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_object (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_STRING_STRING_ARRAY_STRING_STRING (ffi_actual_function func,
                                                                    GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[6], G_TYPE_OBJECT);
  g_value_set_object (&args[6],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_string (&args[1]),
      g_value_get_string (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_string (&args[4]),
      g_value_get_string (&args[5])));
}

static void
emacs_gtk_marshal_OBJECT__STRING_STRING (ffi_actual_function func,
                                         GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[2], G_TYPE_OBJECT);
  g_value_set_object (&args[2],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_OBJECT__STRING (ffi_actual_function func,
                                  GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[1], G_TYPE_OBJECT);
  g_value_set_object (&args[1],
    (*rfunc) (g_value_get_string (&args[0])));
}

static void
emacs_gtk_marshal_OBJECT__NONE (ffi_actual_function func,
                                GValue *args)
{
  __OBJECT_fn rfunc = (__OBJECT_fn) func;

  g_value_init (&args[0], G_TYPE_OBJECT);
  g_value_set_object (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_POINTER__BOOL_INT (ffi_actual_function func,
                                     GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_boolean (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT_FLOAT (ffi_actual_function func,
                                                                GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[6], G_TYPE_POINTER);
  g_value_set_pointer (&args[6],
    (*rfunc) (g_value_get_float (&args[0]),
      g_value_get_float (&args[1]),
      g_value_get_float (&args[2]),
      g_value_get_float (&args[3]),
      g_value_get_float (&args[4]),
      g_value_get_float (&args[5])));
}

static void
emacs_gtk_marshal_POINTER__INT_INT (ffi_actual_function func,
                                    GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__INT (ffi_actual_function func,
                                GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_int (&args[0])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_INT_INT (ffi_actual_function func,
                                           GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[3], G_TYPE_POINTER);
  g_value_set_pointer (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_INT (ffi_actual_function func,
                                       GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_POINTER_INT (ffi_actual_function func,
                                               GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[3], G_TYPE_POINTER);
  g_value_set_pointer (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_POINTER_POINTER_ARRAY_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL (ffi_actual_function func,
                                                                                                       GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[11], G_TYPE_POINTER);
  g_value_set_pointer (&args[11],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1]),
      g_value_get_pointer (&args[2]),
      g_value_get_pointer (&args[3]),
      g_value_get_int (&args[4]),
      g_value_get_pointer (&args[5]),
      g_value_get_pointer (&args[6]),
      g_value_get_pointer (&args[7]),
      g_value_get_pointer (&args[8]),
      g_value_get_boolean (&args[9]),
      g_value_get_boolean (&args[10])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT_POINTER (ffi_actual_function func,
                                           GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__OBJECT (ffi_actual_function func,
                                   GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_POINTER__POINTER (ffi_actual_function func,
                                    GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_POINTER__STRING (ffi_actual_function func,
                                   GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[1], G_TYPE_POINTER);
  g_value_set_pointer (&args[1],
    (*rfunc) (g_value_get_string (&args[0])));
}

static void
emacs_gtk_marshal_POINTER__STRING_INT (ffi_actual_function func,
                                       GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_string (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_POINTER__NONE (ffi_actual_function func,
                                 GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[0], G_TYPE_POINTER);
  g_value_set_pointer (&args[0],
    (*rfunc) ());
}

static void
emacs_gtk_marshal_POINTER__POINTER_POINTER (ffi_actual_function func,
                                            GValue *args)
{
  __POINTER_fn rfunc = (__POINTER_fn) func;

  g_value_init (&args[2], G_TYPE_POINTER);
  g_value_set_pointer (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_pointer (&args[1])));
}

static void
emacs_gtk_marshal_STRING__INT_INT_INT (ffi_actual_function func,
                                       GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[3], G_TYPE_STRING);
  g_value_set_string (&args[3],
    (*rfunc) (g_value_get_int (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_STRING__INT (ffi_actual_function func,
                               GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[1], G_TYPE_STRING);
  g_value_set_string (&args[1],
    (*rfunc) (g_value_get_int (&args[0])));
}

static void
emacs_gtk_marshal_STRING__OBJECT_BOOL (ffi_actual_function func,
                                       GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[2], G_TYPE_STRING);
  g_value_set_string (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_boolean (&args[1])));
}

static void
emacs_gtk_marshal_STRING__OBJECT_FLOAT (ffi_actual_function func,
                                        GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[2], G_TYPE_STRING);
  g_value_set_string (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_float (&args[1])));
}

static void
emacs_gtk_marshal_STRING__OBJECT_INT_INT (ffi_actual_function func,
                                          GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[3], G_TYPE_STRING);
  g_value_set_string (&args[3],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1]),
      g_value_get_int (&args[2])));
}

static void
emacs_gtk_marshal_STRING__OBJECT_INT (ffi_actual_function func,
                                      GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[2], G_TYPE_STRING);
  g_value_set_string (&args[2],
    (*rfunc) (g_value_get_object (&args[0]),
      g_value_get_int (&args[1])));
}

static void
emacs_gtk_marshal_STRING__OBJECT (ffi_actual_function func,
                                  GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[1], G_TYPE_STRING);
  g_value_set_string (&args[1],
    (*rfunc) (g_value_get_object (&args[0])));
}

static void
emacs_gtk_marshal_STRING__POINTER_STRING (ffi_actual_function func,
                                          GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[2], G_TYPE_STRING);
  g_value_set_string (&args[2],
    (*rfunc) (g_value_get_pointer (&args[0]),
      g_value_get_string (&args[1])));
}

static void
emacs_gtk_marshal_STRING__POINTER (ffi_actual_function func,
                                   GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[1], G_TYPE_STRING);
  g_value_set_string (&args[1],
    (*rfunc) (g_value_get_pointer (&args[0])));
}

static void
emacs_gtk_marshal_STRING__NONE (ffi_actual_function func,
                                GValue *args)
{
  __STRING_fn rfunc = (__STRING_fn) func;

  g_value_init (&args[0], G_TYPE_STRING);
  g_value_set_string (&args[0],
    (*rfunc) ());
}

#define FOR_ALL_MARSHALLERS(FROB, FROB_LAST) \
  FROB(432, emacs_gtk_marshal_OBJECT__BOOL_BOOL_INT) \
  FROB(665, emacs_gtk_marshal_BOOL__OBJECT_INT) \
  FROB(1010, emacs_gtk_marshal_POINTER__INT) \
  FROB(1538, emacs_gtk_marshal_POINTER__INT_INT) \
  FROB(1641, emacs_gtk_marshal_STRING__NONE) \
  FROB(2023, emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_INT) \
  FROB(3013, emacs_gtk_marshal_NONE__OBJECT_INT_POINTER) \
  FROB(3107, emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT_INT_INT) \
  FROB(3283, emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY_ARRAY) \
  FROB(3354, emacs_gtk_marshal_POINTER__OBJECT_POINTER) \
  FROB(3687, emacs_gtk_marshal_NONE__INT_INT_INT_INT) \
  FROB(4119, emacs_gtk_marshal_NONE__OBJECT_STRING_STRING) \
  FROB(4482, emacs_gtk_marshal_INT__OBJECT_STRING) \
  FROB(4953, emacs_gtk_marshal_INT__BOOL) \
  FROB(5159, emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT) \
  FROB(5510, emacs_gtk_marshal_NONE__OBJECT_LIST) \
  FROB(5779, emacs_gtk_marshal_BOOL__POINTER) \
  FROB(5940, emacs_gtk_marshal_NONE__OBJECT_OBJECT_FLOAT_INT) \
  FROB(5997, emacs_gtk_marshal_STRING__OBJECT_FLOAT) \
  FROB(6126, emacs_gtk_marshal_INT__OBJECT) \
  FROB(6513, emacs_gtk_marshal_NONE__OBJECT_INT_INT_ARRAY) \
  FROB(6919, emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL) \
  FROB(7184, emacs_gtk_marshal_OBJECT__INT) \
  FROB(7726, emacs_gtk_marshal_OBJECT__STRING_OBJECT) \
  FROB(8119, emacs_gtk_marshal_NONE__INT) \
  FROB(8272, emacs_gtk_marshal_NONE__NONE) \
  FROB(8499, emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_POINTER_POINTER_INT_INT) \
  FROB(8625, emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT) \
  FROB(8888, emacs_gtk_marshal_INT__OBJECT_INT_ARRAY) \
  FROB(9054, emacs_gtk_marshal_OBJECT__OBJECT) \
  FROB(9977, emacs_gtk_marshal_NONE__OBJECT_STRING) \
  FROB(10290, emacs_gtk_marshal_INT__POINTER_STRING_INT) \
  FROB(10503, emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT) \
  FROB(10839, emacs_gtk_marshal_NONE__OBJECT) \
  FROB(10844, emacs_gtk_marshal_POINTER__OBJECT_INT_INT) \
  FROB(11584, emacs_gtk_marshal_OBJECT__STRING_INT_STRING_STRING) \
  FROB(11670, emacs_gtk_marshal_NONE__OBJECT_LIST_INT) \
  FROB(11792, emacs_gtk_marshal_OBJECT__INT_INT_STRING) \
  FROB(12503, emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT) \
  FROB(12547, emacs_gtk_marshal_NONE__POINTER_POINTER_INT_INT) \
  FROB(12900, emacs_gtk_marshal_STRING__POINTER_STRING) \
  FROB(13215, emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_POINTER) \
  FROB(13795, emacs_gtk_marshal_NONE__POINTER_POINTER) \
  FROB(14439, emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT) \
  FROB(14448, emacs_gtk_marshal_NONE__OBJECT_STRING_BOOL) \
  FROB(15146, emacs_gtk_marshal_POINTER__OBJECT_POINTER_INT) \
  FROB(15335, emacs_gtk_marshal_BOOL__OBJECT_POINTER) \
  FROB(15721, emacs_gtk_marshal_NONE__OBJECT_INT_STRING) \
  FROB(15792, emacs_gtk_marshal_OBJECT__INT_BOOL_BOOL) \
  FROB(17065, emacs_gtk_marshal_NONE__OBJECT_STRING_INT_INT_INT) \
  FROB(17509, emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT_BOOL) \
  FROB(18008, emacs_gtk_marshal_FLOAT__OBJECT_FLOAT) \
  FROB(18450, emacs_gtk_marshal_OBJECT__OBJECT_STRING) \
  FROB(18871, emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT) \
  FROB(19536, emacs_gtk_marshal_STRING__OBJECT_INT_INT) \
  FROB(20812, emacs_gtk_marshal_STRING__POINTER) \
  FROB(21285, emacs_gtk_marshal_NONE__POINTER_INT_INT) \
  FROB(21342, emacs_gtk_marshal_INT__POINTER_INT) \
  FROB(21557, emacs_gtk_marshal_NONE__OBJECT_POINTER) \
  FROB(21680, emacs_gtk_marshal_INT__OBJECT_OBJECT) \
  FROB(21774, emacs_gtk_marshal_POINTER__STRING) \
  FROB(22007, emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT) \
  FROB(22411, emacs_gtk_marshal_NONE__POINTER_STRING) \
  FROB(22691, emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER) \
  FROB(22930, emacs_gtk_marshal_OBJECT__POINTER_STRING) \
  FROB(23124, emacs_gtk_marshal_NONE__OBJECT_FLOAT) \
  FROB(23189, emacs_gtk_marshal_NONE__POINTER_INT) \
  FROB(23449, emacs_gtk_marshal_STRING__OBJECT_BOOL) \
  FROB(24398, emacs_gtk_marshal_INT__POINTER) \
  FROB(25463, emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING_INT) \
  FROB(25575, emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_STRING) \
  FROB(25932, emacs_gtk_marshal_POINTER__OBJECT_INT) \
  FROB(26045, emacs_gtk_marshal_LIST__OBJECT) \
  FROB(26910, emacs_gtk_marshal_POINTER__STRING_INT) \
  FROB(26971, emacs_gtk_marshal_FLOAT__OBJECT) \
  FROB(27175, emacs_gtk_marshal_NONE__OBJECT_OBJECT) \
  FROB(28145, emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER) \
  FROB(28593, emacs_gtk_marshal_NONE__OBJECT_INT_INT_FLOAT_FLOAT) \
  FROB(28975, emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING) \
  FROB(29047, emacs_gtk_marshal_NONE__OBJECT_INT_INT) \
  FROB(29159, emacs_gtk_marshal_NONE__OBJECT_INT) \
  FROB(29882, emacs_gtk_marshal_INT__STRING_STRING_INT_ARRAY) \
  FROB(29884, emacs_gtk_marshal_OBJECT__POINTER_POINTER) \
  FROB(30181, emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT_INT) \
  FROB(30201, emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING_INT_INT_INT_INT_INT) \
  FROB(30337, emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_POINTER_POINTER) \
  FROB(30533, emacs_gtk_marshal_NONE__POINTER_STRING_STRING) \
  FROB(31573, emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER) \
  FROB(31888, emacs_gtk_marshal_INT__INT_INT) \
  FROB(31941, emacs_gtk_marshal_NONE__OBJECT_POINTER_INT) \
  FROB(32041, emacs_gtk_marshal_NONE__OBJECT_OBJECT_STRING) \
  FROB(32919, emacs_gtk_marshal_NONE__OBJECT_INT_OBJECT) \
  FROB(32937, emacs_gtk_marshal_OBJECT__INT_INT_BOOL) \
  FROB(33031, emacs_gtk_marshal_BOOL__OBJECT_STRING) \
  FROB(33829, emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING_INT_POINTER_POINTER) \
  FROB(34471, emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT_INT_INT_INT_INT_INT_INT) \
  FROB(34727, emacs_gtk_marshal_INT__NONE) \
  FROB(35479, emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT) \
  FROB(35648, emacs_gtk_marshal_OBJECT__OBJECT_OBJECT) \
  FROB(36031, emacs_gtk_marshal_NONE__POINTER_POINTER_POINTER_INT_INT_STRING_INT) \
  FROB(36718, emacs_gtk_marshal_OBJECT__OBJECT_INT) \
  FROB(37442, emacs_gtk_marshal_NONE__OBJECT_INT_BOOL) \
  FROB(37502, emacs_gtk_marshal_STRING__INT) \
  FROB(38890, emacs_gtk_marshal_OBJECT__STRING_STRING_STRING_ARRAY_STRING_STRING) \
  FROB(38972, emacs_gtk_marshal_POINTER__OBJECT) \
  FROB(39063, emacs_gtk_marshal_NONE__OBJECT_INT_INT_INT_INT) \
  FROB(39326, emacs_gtk_marshal_POINTER__POINTER_POINTER) \
  FROB(39429, emacs_gtk_marshal_NONE__POINTER) \
  FROB(39561, emacs_gtk_marshal_BOOL__OBJECT_OBJECT_OBJECT) \
  FROB(39897, emacs_gtk_marshal_NONE__OBJECT_INT_INT_STRING) \
  FROB(39942, emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT) \
  FROB(40578, emacs_gtk_marshal_BOOL__NONE) \
  FROB(40914, emacs_gtk_marshal_NONE__OBJECT_BOOL) \
  FROB(41280, emacs_gtk_marshal_STRING__OBJECT_INT) \
  FROB(42034, emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT) \
  FROB(42415, emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_POINTER_STRING_INT) \
  FROB(44034, emacs_gtk_marshal_NONE__BOOL) \
  FROB(44362, emacs_gtk_marshal_OBJECT__INT_ARRAY) \
  FROB(44727, emacs_gtk_marshal_POINTER__BOOL_INT) \
  FROB(44823, emacs_gtk_marshal_OBJECT__NONE) \
  FROB(45538, emacs_gtk_marshal_NONE__OBJECT_BOOL_INT) \
  FROB(45607, emacs_gtk_marshal_NONE__OBJECT_OBJECT_BOOL_BOOL_INT_INT) \
  FROB(45666, emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT_INT) \
  FROB(46466, emacs_gtk_marshal_OBJECT__STRING_FLOAT_FLOAT_FLOAT_BOOL) \
  FROB(46564, emacs_gtk_marshal_NONE__OBJECT_INT_FLOAT) \
  FROB(46919, emacs_gtk_marshal_NONE__INT_INT) \
  FROB(47820, emacs_gtk_marshal_INT__OBJECT_POINTER) \
  FROB(47986, emacs_gtk_marshal_INT__OBJECT_INT_STRING) \
  FROB(48126, emacs_gtk_marshal_INT__OBJECT_INT) \
  FROB(48364, emacs_gtk_marshal_INT__OBJECT_POINTER_INT_INT) \
  FROB(48674, emacs_gtk_marshal_INT__POINTER_STRING) \
  FROB(49116, emacs_gtk_marshal_INT__OBJECT_POINTER_INT) \
  FROB(49171, emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER) \
  FROB(49239, emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT) \
  FROB(49523, emacs_gtk_marshal_NONE__OBJECT_POINTER_POINTER_INT_INT_INT_INT_INT_INT) \
  FROB(49630, emacs_gtk_marshal_OBJECT__POINTER) \
  FROB(49822, emacs_gtk_marshal_STRING__INT_INT_INT) \
  FROB(50037, emacs_gtk_marshal_POINTER__NONE) \
  FROB(50181, emacs_gtk_marshal_NONE__OBJECT_OBJECT_POINTER) \
  FROB(50214, emacs_gtk_marshal_NONE__POINTER_POINTER_BOOL_INT_INT_INT_INT_INT_INT) \
  FROB(50229, emacs_gtk_marshal_BOOL__OBJECT_OBJECT) \
  FROB(50650, emacs_gtk_marshal_POINTER__OBJECT_POINTER_POINTER_ARRAY_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL) \
  FROB(50704, emacs_gtk_marshal_POINTER__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT_FLOAT) \
  FROB(50995, emacs_gtk_marshal_NONE__OBJECT_INT_INT_POINTER_POINTER) \
  FROB(51406, emacs_gtk_marshal_INT__POINTER_STRING_STRING) \
  FROB(51880, emacs_gtk_marshal_INT__OBJECT_ARRAY) \
  FROB(52452, emacs_gtk_marshal_NONE__POINTER_BOOL) \
  FROB(52615, emacs_gtk_marshal_NONE__OBJECT_STRING_POINTER_INT_INT_INT) \
  FROB(54464, emacs_gtk_marshal_INT__STRING) \
  FROB(55310, emacs_gtk_marshal_INT__OBJECT_INT_INT) \
  FROB(55319, emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING_INT_POINTER_POINTER) \
  FROB(55441, emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT) \
  FROB(56064, emacs_gtk_marshal_OBJECT__STRING_STRING) \
  FROB(56523, emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_STRING) \
  FROB(56661, emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_INT) \
  FROB(57120, emacs_gtk_marshal_OBJECT__INT_INT) \
  FROB(57392, emacs_gtk_marshal_OBJECT__STRING) \
  FROB(57426, emacs_gtk_marshal_OBJECT__OBJECT_STRING_INT_INT_INT_INT) \
  FROB(57671, emacs_gtk_marshal_NONE__OBJECT_OBJECT_INT_INT) \
  FROB(58377, emacs_gtk_marshal_BOOL__OBJECT) \
  FROB(58458, emacs_gtk_marshal_OBJECT__INT_INT_ARRAY) \
  FROB(58926, emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT_FLOAT_FLOAT) \
  FROB(58947, emacs_gtk_marshal_NONE__OBJECT_POINTER_STRING_INT_POINTER_POINTER_POINTER_POINTER_BOOL_BOOL) \
  FROB(59584, emacs_gtk_marshal_POINTER__POINTER) \
  FROB(60976, emacs_gtk_marshal_STRING__OBJECT) \
  FROB(61307, emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_BOOL) \
  FROB(61620, emacs_gtk_marshal_NONE__OBJECT_POINTER_BOOL) \
  FROB(61824, emacs_gtk_marshal_INT__INT) \
  FROB(62391, emacs_gtk_marshal_NONE__OBJECT_OBJECT_OBJECT_OBJECT_INT) \
  FROB(62734, emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT) \
  FROB(62975, emacs_gtk_marshal_NONE__OBJECT_POINTER_INT_FLOAT_FLOAT) \
  FROB(63403, emacs_gtk_marshal_OBJECT__OBJECT_FLOAT_INT) \
  FROB(63766, emacs_gtk_marshal_BOOL__POINTER_BOOL) \
  FROB(63833, emacs_gtk_marshal_OBJECT__BOOL_INT) \
  FROB(64372, emacs_gtk_marshal_OBJECT__FLOAT_FLOAT_FLOAT_FLOAT) \
  FROB(64822, emacs_gtk_marshal_LIST__NONE) \
  FROB_LAST(65483, emacs_gtk_marshal_NONE__OBJECT_FLOAT_FLOAT_FLOAT_FLOAT)

/* emacs-marshal.c ends here. */
